<?php

use NlpTools\Tokenizers\WhitespaceTokenizer;
use NlpTools\Classifiers\MultinomialNBClassifier;

// autoload.php generated by Composer
require 'vendor/autoload.php';

class CooccurrenceAnalyzer {

    private $textFile;
    private $stopWords = ['und', 'oder', 'ist', 'die', 'der']; // Füge hier weitere Stoppwörter hinzu
    private $posTagger;

    public function __construct($textFile) {
        $this->textFile = $textFile;
        $this->posTagger = new WhitespaceTokenizer();
    }

    public function analyzeCooccurrences($windowSize = 2, $includeBigrams = true, $posFilter = null) {
        $text = file_get_contents($this->textFile);

        // Normalisiere den Text und entferne Stoppwörter
        $words = $this->preprocessText($text);

        if ($includeBigrams) {
            $bigrams = $this->generateBigrams($words);
            $words = array_merge($words, $bigrams);
        }

        $cooccurrences = [];

        for ($i = 0; $i < count($words); $i++) {
            $currentWord = $words[$i];

            if ($posFilter && $posFilter !== $this->getPartOfSpeech($currentWord)) {
                continue; // Überspringe Wörter, die nicht der gewünschten Wortart entsprechen
            }

            $start = max(0, $i - $windowSize);
            $end = min(count($words) - 1, $i + $windowSize);

            for ($j = $start; $j <= $end; $j++) {
                $targetWord = $words[$j];

                if ($currentWord !== $targetWord) {
                    $cooccurrence = $currentWord . ' - ' . $targetWord;

                    if (!isset($cooccurrences[$cooccurrence])) {
                        $cooccurrences[$cooccurrence] = 1;
                    } else {
                        $cooccurrences[$cooccurrence]++;
                    }
                }
            }
        }

        arsort($cooccurrences);

        foreach ($cooccurrences as $cooccurrence => $frequency) {
            echo "$cooccurrence: $frequency Mal\n";
        }
    }

    private function preprocessText($text) {
        // Kleinschreibung
        $text = strtolower($text);
        
        // Ersetze Satzzeichen durch Leerzeichen
        $text = str_replace(["\r\n", "\r", "\n", ".", ",", "(", ")", "\"", "'", "?", "!", ";", ":"], ' ', $text);

        // Entferne Stoppwörter
        $text = ' ' . $text . ' ';
        foreach ($this->stopWords as $stopWord) {
            $text = str_replace(' ' . $stopWord . ' ', ' ', $text);
        }

        // Normalisiere Wörter
        $words = str_word_count($text, 1);

        return $words;
    }

    private function generateBigrams($words) {
        $bigrams = [];
        for ($i = 0; $i < count($words) - 1; $i++) {
            $bigram = $words[$i] . ' ' . $words[$i + 1];
            $bigrams[] = $bigram;
        }
        return $bigrams;
    }

    private function getPartOfSpeech($word) {
        // Verwende die WhitespaceTokenizer-Bibliothek für einfaches POS-Tagging
        $tags = $this->posTagger->tag([$word]);
        
        // Das erste Element enthält das POS-Tag
        return reset($tags)[1];
    }
}

// Beispiel für die Verwendung des Tools:

$textFile = "path/to/textfile.txt";

$cooccurrenceAnalyzer = new CooccurrenceAnalyzer($textFile);
$cooccurrenceAnalyzer->analyzeCooccurrences(2, true, 'NN'); // Beispiel: Fenstergröße von 2, Berücksichtigung von Bigrammen, nur Substantive
